name: hd_info_getter
description: A command-line application to retrieve and calculate rimmap info from headerfiles.
Author: KimAlex
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.5

# Afhængigheder for grundlæggende pakker
dependencies:
  json_annotation: ^4.3.0

# Afhængigheder for filoperationer
  path: ^1.8.3
  file: ^7.0.0

# Add regular dependencies here.
  args: ^2.4.2
  http: ^1.1.0
  
# Afhængigheder for logging
  logging: ^1.2.0
  
# Afhængigheder for config
  yaml: ^3.1.2
  async: ^2.11.0
  

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0
  mockito: ^5.4.3
  